version: '3'

services:
  fastapi:
    build: backend/
    ports:
      - 8600:8500
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
        - ./data:/app/data/
        - ./config:/app/config
        - ./models:/app/models
        - ./report:/app/report

  streamlit:
    build: frontend/
    depends_on:
      - fastapi
    ports:
        - 8601:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
        - ./data:/app/data/
        - ./config:/app/config
        - ./models:/app/models
        - ./report:/app/report

networks:
  deploy_network:
    driver: bridge
